apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
  namespace: interview-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: my-api
      containers:
        - name: my-api
          image: arthurburle/interview-test:20221211231442
          ports:
            - containerPort: 3000
              name: http-api-svc
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: my-api
  namespace: interview-test
spec:
  type: NodePort
  selector:
    app: my-api
  ports:
    - name: http-api-svc
      port: 3000
      targetPort: 3000
